import {useEffect,useMemo,useState} from 'react'
import {Activity, AlertTriangle, BarChart3, Download, FileText, Map, RefreshCw, ShieldCheck, Timer, TrendingUp} from 'lucide-react'
import {API,api,apiBlob,token,UserMe} from './api'

type KPI={period_from:string;period_to:string;total_events:number;active_events:number;critical_events:number;high_events:number;warning_events:number;unique_tracks:number;false_positive_rate:number;evidence_coverage_rate:number;ack_sla_met_rate:number;resolution_sla_met_rate:number;escalation_rate:number;avg_ack_seconds:number|null;avg_resolution_seconds:number|null;compliance_rate:number|null;archived_qa_events:number}
type Trend={bucket:string;events:number;critical:number;high:number;warning:number;false_positive:number;escalated:number}
type Risk={key:string;label:string;count:number;share:number}
type Heat={zone_id:string;zone_code:string;zone_name:string;camera_id:string;camera_code:string;polygon_points:{x:number;y:number}[];event_count:number;critical_count:number;intensity:number}
type Cleanup={total_runs:number;last_run_at:string|null;archived_events:number;compliance_enabled_cameras:number;qa_active_events:number}
type Report={generated_at:string;title:string;summary:KPI;top_ppe:Risk[];top_zones:Risk[];top_cameras:Risk[];recommendations:string[]}

function pct(v:number){return `${v.toFixed(1)}%`} function secs(v:number|null){if(v==null)return '—';if(v<60)return `${Math.round(v)}s`;return `${(v/60).toFixed(1)}m`}
export default function AnalyticsPage({me}:{me:UserMe}){
 const canRead=me.permission_codes.includes('analytics.read')||me.role_codes.includes('SUPERADMIN'),canExport=me.permission_codes.includes('analytics.export')||me.role_codes.includes('SUPERADMIN')
 const [kpi,setKpi]=useState<KPI|null>(null),[trend,setTrend]=useState<Trend[]>([]),[ppe,setPpe]=useState<Risk[]>([]),[zones,setZones]=useState<Risk[]>([]),[cams,setCams]=useState<Risk[]>([]),[heat,setHeat]=useState<Heat[]>([]),[cleanup,setCleanup]=useState<Cleanup|null>(null),[report,setReport]=useState<Report|null>(null),[includeQA,setIncludeQA]=useState(false),[days,setDays]=useState(30),[busy,setBusy]=useState(false)
 const query=`?include_qa=${includeQA}`
 async function refresh(){setBusy(true);try{const [a,b,c,d,e,f,g]=await Promise.all([api<KPI>('/analytics/executive'+query),api<Trend[]>('/analytics/trend'+query),api<Risk[]>('/analytics/top-risks'+query+'&dimension=ppe'),api<Risk[]>('/analytics/top-risks'+query+'&dimension=zone'),api<Risk[]>('/analytics/top-risks'+query+'&dimension=camera'),api<Heat[]>('/analytics/heatmap'+query),api<Cleanup>('/analytics/cleanup-status')]);setKpi(a);setTrend(b);setPpe(c);setZones(d);setCams(e);setHeat(f);setCleanup(g);setReport(await api<Report>('/analytics/report'+query))}finally{setBusy(false)}}
 useEffect(()=>{if(canRead)refresh()},[includeQA])
 const maxTrend=Math.max(1,...trend.map(x=>x.events)); const maxHeat=Math.max(1,...heat.map(x=>x.event_count))
 async function download(){const b=await apiBlob('/analytics/export.csv'+query);const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='hys_vision_analytics.csv';a.click();URL.revokeObjectURL(u)}
 if(!canRead)return <div className="vision-no-camera">Sin permiso para consultar analítica ejecutiva.</div>
 return <div className="analytics-workspace">
  <section className="analytics-command"><div><div className="eyebrow">BLOQUE 8 · v0.9.0 · INTELIGENCIA OPERATIVA</div><h3>Dashboard ejecutivo, KPIs y analítica histórica</h3><p>Los datos QA archivados quedan fuera de los indicadores por defecto. Evidencias, auditoría y trazabilidad se preservan para consulta histórica.</p></div><div className="cleanup-badge"><ShieldCheck/><span>PILOTO LIMPIO<b>{cleanup?.archived_events??'—'} QA archivados</b><small>{cleanup?.compliance_enabled_cameras===0?'Cumplimiento demo detenido':'Revisar cámaras demo'}</small></span></div></section>
  <div className="analytics-toolbar"><label><input type="checkbox" checked={includeQA} onChange={e=>setIncludeQA(e.target.checked)}/> Incluir QA archivado</label><button onClick={refresh}><RefreshCw size={14}/>{busy?'ACTUALIZANDO':'ACTUALIZAR'}</button>{canExport&&<button onClick={download}><Download size={14}/> EXPORTAR CSV</button>}</div>
  <section className="kpi-grid">
   <K icon={Activity} label="EVENTOS" value={kpi?.total_events??'—'} sub={`${kpi?.active_events??0} activos`}/><K icon={ShieldCheck} label="CUMPLIMIENTO" value={kpi?.compliance_rate==null?'—':pct(kpi.compliance_rate)} sub="evaluaciones observables"/><K icon={Timer} label="SLA ACK" value={kpi?pct(kpi.ack_sla_met_rate):'—'} sub={`prom. ${secs(kpi?.avg_ack_seconds??null)}`}/><K icon={TrendingUp} label="SLA RESOLUCIÓN" value={kpi?pct(kpi.resolution_sla_met_rate):'—'} sub={`prom. ${secs(kpi?.avg_resolution_seconds??null)}`}/><K icon={AlertTriangle} label="ESCALAMIENTO" value={kpi?pct(kpi.escalation_rate):'—'} sub="eventos escalados"/><K icon={FileText} label="EVIDENCIA" value={kpi?pct(kpi.evidence_coverage_rate):'—'} sub="cobertura documental"/>
  </section>
  <section className="analytics-grid"><div className="analytics-panel wide"><div className="panel-title"><span>TENDENCIA HISTÓRICA</span><em>ÚLTIMOS 30 DÍAS</em></div><div className="trend-bars">{trend.length?trend.map(x=><div key={x.bucket} className="trend-col" title={`${x.bucket}: ${x.events}`}><div style={{height:`${Math.max(4,100*x.events/maxTrend)}%`}}><span>{x.events}</span></div><small>{x.bucket.slice(5)}</small></div>):<div className="analytics-empty">Sin eventos operativos en el período.</div>}</div></div><div className="analytics-panel"><div className="panel-title"><span>RIESGO POR EPP</span><em>TOP</em></div><RiskList rows={ppe}/></div></section>
  <section className="analytics-grid"><div className="analytics-panel"><div className="panel-title"><span>ZONAS CON MAYOR EXPOSICIÓN</span><em>TOP</em></div><RiskList rows={zones}/></div><div className="analytics-panel"><div className="panel-title"><span>CÁMARAS CON MÁS EVENTOS</span><em>TOP</em></div><RiskList rows={cams}/></div></section>
  <section className="analytics-panel heat-panel"><div className="panel-title"><span>HEATMAP POR ZONAS</span><em>{heat.length} zonas</em></div>{heat.length?<div className="heat-layout"><svg viewBox="0 0 1000 562" className="heat-svg">{heat.map(z=><polygon key={z.zone_id} points={z.polygon_points.map(p=>`${p.x*1000},${p.y*562}`).join(' ')} style={{opacity:.15+.7*z.intensity}}><title>{z.zone_code}: {z.event_count} eventos</title></polygon>)}</svg><div className="heat-list">{[...heat].sort((a,b)=>b.event_count-a.event_count).slice(0,8).map(z=><div key={z.zone_id}><span>{z.camera_code} · {z.zone_code}</span><b>{z.event_count}</b><small>{z.critical_count} críticos</small></div>)}</div></div>:<div className="analytics-empty"><Map/>Sin eventos operativos para construir el heatmap.</div>}</section>
  <section className="analytics-panel report-panel"><div className="panel-title"><span>REPORTE EJECUTIVO</span><em>GENERADO EN TIEMPO REAL</em></div><div className="report-body"><div><h4>{report?.title}</h4><p>Eventos: <b>{report?.summary.total_events??0}</b> · Falsos positivos: <b>{report?pct(report.summary.false_positive_rate):'—'}</b> · QA archivado preservado: <b>{report?.summary.archived_qa_events??0}</b></p></div><div>{report?.recommendations.map(x=><p key={x}>• {x}</p>)}</div></div></section>
 </div>}
function K({icon:Icon,label,value,sub}:{icon:any;label:string;value:any;sub:string}){return <div className="kpi-card"><Icon/><span>{label}</span><b>{value}</b><small>{sub}</small></div>}
function RiskList({rows}:{rows:Risk[]}){return <div className="risk-list">{rows.length?rows.slice(0,6).map(x=><div key={x.key}><span>{x.label}</span><b>{x.count}</b><i><u style={{width:`${Math.max(3,x.share)}%`}}/></i><small>{x.share.toFixed(1)}%</small></div>):<div className="analytics-empty">Sin datos operativos.</div>}</div>}
