import {useEffect,useMemo,useRef,useState} from 'react'
import {Camera as CameraIcon, CircleDot, Gauge, MonitorPlay, Plus, RefreshCw, ShieldCheck, Video, VideoOff} from 'lucide-react'
import {api, token, UserMe} from './api'

type Org={id:string;code:string;name:string}
type Site={id:string;organization_id:string;code:string;name:string}
type Plant={id:string;organization_id:string;site_id:string;code:string;name:string}
type Sector={id:string;organization_id:string;site_id:string;plant_id:string;code:string;name:string}
type Cam={id:string;organization_id:string;site_id:string;plant_id:string;sector_id:string;code:string;name:string;description?:string|null;location?:string|null;source_type:'RTSP'|'DEMO_FILE';rtsp_url_masked?:string|null;credentials_configured:boolean;manufacturer?:string|null;model_name?:string|null;capture_fps:number;measured_fps?:number|null;latency_ms?:number|null;status:string;active:boolean;ai_enabled:boolean;last_connection_at?:string|null;last_frame_at?:string|null;last_error?:string|null}
type Summary={total:number;online:number;offline:number;degraded:number;no_video:number;auth_error:number;demo:number}
type Worker={status:string;heartbeat_age_seconds:number|null}

const API_BASE=(import.meta.env.VITE_API_BASE_URL||'http://localhost:8160/api/v1').replace(/\/$/,'')

function statusLabel(status:string){return status.replaceAll('_',' ')}
function dateTime(v?:string|null){if(!v)return '—';try{return new Date(v).toLocaleString()}catch{return v}}

function LivePreview({camera}:{camera:Cam|null}){
 const [src,setSrc]=useState<string|null>(null),[state,setState]=useState('SIN FRAME'); const previous=useRef<string|null>(null)
 useEffect(()=>{let stop=false;async function tick(){if(!camera){setSrc(null);setState('SIN CÁMARA');return}try{const t=token();const endpoint=camera.ai_enabled?`${API_BASE}/vision/cameras/${camera.id}/overlay.jpg`:`${API_BASE}/cameras/${camera.id}/snapshot.jpg`;const r=await fetch(endpoint,{headers:t?{Authorization:`Bearer ${t}`}:{}});if(!r.ok)throw new Error(String(r.status));const blob=await r.blob();const u=URL.createObjectURL(blob);if(stop){URL.revokeObjectURL(u);return}if(previous.current)URL.revokeObjectURL(previous.current);previous.current=u;setSrc(u);setState('LIVE')}catch{if(!stop)setState(camera.active?'ESPERANDO FRAME':'DESACTIVADA')}}tick();const timer=setInterval(tick,650);return()=>{stop=true;clearInterval(timer);if(previous.current){URL.revokeObjectURL(previous.current);previous.current=null}}},[camera?.id,camera?.active])
 return <div className="camera-preview"><div className="camera-preview-head"><div><span>{camera?.code||'CAM'}</span><strong>{camera?.name||'Seleccione una cámara'}</strong></div><b className={`camera-state ${camera?.status?.toLowerCase()||''}`}><CircleDot size={12}/>{camera?.status||state}</b></div><div className="video-stage">{src?<img src={src} alt={`Vista ${camera?.name}`}/>:<div className="video-empty"><VideoOff/><strong>{state}</strong><small>El worker publica frames reales cuando la fuente está disponible.</small></div>}<div className="video-overlay"><span>{camera?.source_type==='DEMO_FILE'?'DEMO EPP REAL':'RTSP'}</span><span>{camera?.ai_enabled?'OVERLAY IA':'RAW'}</span><span>{camera?.measured_fps!=null?`${camera.measured_fps.toFixed(1)} FPS CAPTURA`:'— FPS'}</span><span>{camera?.latency_ms?`${camera.latency_ms.toFixed(0)} ms`:'— ms'}</span></div></div>{camera&&<div className="camera-technical"><div><span>ÚLTIMO FRAME</span><b>{dateTime(camera.last_frame_at)}</b></div><div><span>FUENTE</span><b>{camera.rtsp_url_masked||'Video EPP real · reproducción tiempo real'}</b></div><div><span>IA</span><b>{camera.ai_enabled?'PERSON + EPP SHADOW':'IA DESACTIVADA'}</b></div></div>}</div>
}

export default function CamerasPage({me}:{me:UserMe}){
 const [orgs,setOrgs]=useState<Org[]>([]),[sites,setSites]=useState<Site[]>([]),[plants,setPlants]=useState<Plant[]>([]),[sectors,setSectors]=useState<Sector[]>([]),[cams,setCams]=useState<Cam[]>([]),[summary,setSummary]=useState<Summary|null>(null),[worker,setWorker]=useState<Worker|null>(null)
 const [orgId,setOrgId]=useState(me.organization_id||''),[siteId,setSiteId]=useState(''),[plantId,setPlantId]=useState(''),[sectorId,setSectorId]=useState(''),[selected,setSelected]=useState<string>(''),[msg,setMsg]=useState('')
 const [sourceType,setSourceType]=useState<'DEMO_FILE'|'RTSP'>('DEMO_FILE'),[code,setCode]=useState('DEMO01'),[name,setName]=useState('Cámara Demo'),[url,setUrl]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[captureFps,setCaptureFps]=useState(5)
 const canManage=me.permission_codes.includes('camera.manage')||me.role_codes.includes('SUPERADMIN')
 const selectedCam=useMemo(()=>cams.find(x=>x.id===selected)||cams[0]||null,[cams,selected])
 async function refreshCameras(){const [c,s,w]=await Promise.all([api<Cam[]>('/cameras'),api<Summary>('/cameras/summary'),api<Worker>('/cameras/worker')]);setCams(c);setSummary(s);setWorker(w);if(!selected&&c[0])setSelected(c[0].id)}
 async function loadStructure(){const o=await api<Org[]>('/organizations');setOrgs(o);const current=orgId||me.organization_id||o[0]?.id||'';setOrgId(current);if(current){const si=await api<Site[]>(`/sites?organization_id=${current}`);setSites(si);setSiteId(si[0]?.id||'')}}
 useEffect(()=>{loadStructure();refreshCameras();const t=setInterval(refreshCameras,3000);return()=>clearInterval(t)},[])
 useEffect(()=>{if(!orgId)return;api<Site[]>(`/sites?organization_id=${orgId}`).then(x=>{setSites(x);setSiteId(x[0]?.id||'')})},[orgId])
 useEffect(()=>{if(!siteId){setPlants([]);return}api<Plant[]>(`/plants?site_id=${siteId}`).then(x=>{setPlants(x);setPlantId(x[0]?.id||'')})},[siteId])
 useEffect(()=>{if(!plantId){setSectors([]);return}api<Sector[]>(`/sectors?plant_id=${plantId}`).then(x=>{setSectors(x);setSectorId(x[0]?.id||'')})},[plantId])
 async function createCamera(){setMsg('');try{await api('/cameras',{method:'POST',body:JSON.stringify({sector_id:sectorId,code,name,source_type:sourceType,rtsp_url:sourceType==='RTSP'?url:null,username:username||null,password:password||null,capture_fps:captureFps,ai_enabled:false})});setMsg('Cámara registrada. El worker tomará la fuente automáticamente.');setPassword('');await refreshCameras()}catch(e){setMsg((e as Error).message)}}
 async function toggle(cam:Cam){try{await api(`/cameras/${cam.id}`,{method:'PATCH',body:JSON.stringify({active:!cam.active})});await refreshCameras()}catch(e){setMsg((e as Error).message)}}
 return <div className="camera-workspace"><section className="camera-command"><div><div className="eyebrow">INGESTA DE VIDEO · BLOQUE 10</div><h3>Cámaras y fuentes en tiempo real</h3><p>RTSP y fuentes de prueba operan en un worker independiente. DEMO01 usa ahora el video real EPP del Bloque 9; el antiguo demo de persona ya no es la fuente predeterminada.</p></div><div className={`worker-chip ${worker?.status||'offline'}`}><span className="pulse"/><div><small>CAMERA WORKER</small><strong>{worker?.status?.toUpperCase()||'CONSULTANDO'}</strong></div></div></section>
 <section className="camera-metrics"><div><CameraIcon/><span>CÁMARAS</span><strong>{summary?.total??'—'}</strong></div><div><Video/><span>ONLINE</span><strong>{summary?.online??'—'}</strong></div><div><VideoOff/><span>OFFLINE / SIN VIDEO</span><strong>{summary?(summary.offline+summary.no_video):'—'}</strong></div><div><MonitorPlay/><span>DEMO</span><strong>{summary?.demo??'—'}</strong></div></section>
 <section className="camera-layout"><div className="camera-left"><LivePreview camera={selectedCam}/><div className="camera-list"><div className="panel-title"><span>INVENTARIO DE CÁMARAS</span><button className="icon-button" onClick={refreshCameras}><RefreshCw size={15}/>Actualizar</button></div>{cams.length===0?<div className="camera-empty"><CameraIcon/><b>No hay cámaras registradas</b><span>Creá una Demo Camera para validar el flujo sin hardware físico.</span></div>:cams.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={selectedCam?.id===c.id?'camera-row selected':'camera-row'}><div className={`camera-dot ${c.status.toLowerCase()}`}/><div><strong>{c.code} · {c.name}</strong><small>{c.source_type==='DEMO_FILE'?'VIDEO EPP REAL':c.rtsp_url_masked||'RTSP'} · {c.location||'sin ubicación específica'}</small></div><span className="row-health">{statusLabel(c.status)}</span>{canManage&&<span className="row-action" onClick={e=>{e.stopPropagation();toggle(c)}}>{c.active?'DESACTIVAR':'ACTIVAR'}</span>}</button>)}</div></div>
 {canManage&&<aside className="camera-config"><div className="panel-title"><span>NUEVA CÁMARA</span><em>REAL / DEMO</em></div><label>Cliente</label><select value={orgId} onChange={e=>setOrgId(e.target.value)} disabled={!!me.organization_id}>{orgs.map(o=><option key={o.id} value={o.id}>{o.code} — {o.name}</option>)}</select><label>Establecimiento</label><select value={siteId} onChange={e=>setSiteId(e.target.value)}>{sites.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><label>Planta</label><select value={plantId} onChange={e=>setPlantId(e.target.value)}>{plants.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><label>Sector</label><select value={sectorId} onChange={e=>setSectorId(e.target.value)}>{sectors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="source-switch"><button className={sourceType==='DEMO_FILE'?'active':''} onClick={()=>{setSourceType('DEMO_FILE');if(!code) setCode('DEMO01')}}><MonitorPlay/>Demo MP4</button><button className={sourceType==='RTSP'?'active':''} onClick={()=>setSourceType('RTSP')}><Video/>RTSP</button></div><label>Código</label><input value={code} onChange={e=>setCode(e.target.value)} placeholder="CAM-01"/><label>Nombre</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ingreso principal"/>{sourceType==='RTSP'&&<><label>URL RTSP</label><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="rtsp://192.168.1.50/stream"/><div className="credential-grid"><div><label>Usuario</label><input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off"/></div><div><label>Contraseña</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="new-password"/></div></div></>}<label>FPS de captura</label><input value={captureFps} onChange={e=>setCaptureFps(Number(e.target.value))} type="number" min="0.2" max="30" step="0.2"/><div className="security-note"><ShieldCheck/><span>{sourceType==='DEMO_FILE'?'Usará el video EPP real del Bloque 9/10 en loop. El demo anterior queda archivado.':'La contraseña RTSP se cifra con Fernet antes de guardarse.'}</span></div><button className="primary add-camera" disabled={!sectorId||!code||!name||(sourceType==='RTSP'&&!url)} onClick={createCamera}><Plus/>REGISTRAR CÁMARA</button>{msg&&<div className="camera-message">{msg}</div>}</aside>}</section></div>
}
