import {useEffect,useMemo,useRef,useState} from 'react'
import {CheckCircle2, Database, FileVideo2, Images, MousePointer2, RefreshCw, ScanSearch, ShieldCheck, Trash2, Upload, Video, XCircle} from 'lucide-react'
import {API,api,token,UserMe} from './api'

type Dataset={id:string;code:string;name:string;license_name:string}
type Cam={id:string;organization_id:string;code:string;name:string;status:string}
type Ann={id?:string;class_code:string;x:number;y:number;width:number;height:number;verified?:boolean}
type Frame={id:string;camera_id?:string;source_type:string;source_ref?:string;frame_index?:number;sha256:string;width:number;height:number;curation_status:string;ground_truth_status:string;annotations:Ann[]}
type Work={dataset:Dataset;stats:Record<string,number>;classes:string[];frames:Frame[]}
type Overview={datasets:Dataset[]}
type Org={id:string;code:string;name:string}
type ShadowCam={camera_id:string;camera_code:string;camera_name:string;samples:number;agreements:number;agreement_ratio:number;by_ppe:Record<string,{samples:number;agreements:number;agreement_ratio:number}>}

type Draft={class_code:string;x:number;y:number;width:number;height:number}

function imageUrl(id:string){return `${API}/ml/frames/${id}/image`}

function AuthThumb({id}:{id:string}){
 const [src,setSrc]=useState('')
 useEffect(()=>{let dead=false,u='';const h=new Headers();const t=token();if(t)h.set('Authorization',`Bearer ${t}`);fetch(imageUrl(id),{headers:h}).then(r=>r.blob()).then(b=>{if(dead)return;u=URL.createObjectURL(b);setSrc(u)}).catch(()=>{});return()=>{dead=true;if(u)URL.revokeObjectURL(u)}},[id])
 return src?<img src={src}/>:<div className="frame-thumb-empty"/>
}

function LabelCanvas({frame,activeClass,onChange}:{frame:Frame;activeClass:string;onChange:(a:Draft[])=>void}){
 const canvas=useRef<HTMLCanvasElement|null>(null),start=useRef<{x:number;y:number}|null>(null),[draft,setDraft]=useState<Draft[]>(frame.annotations.map(a=>({...a})))
 useEffect(()=>setDraft(frame.annotations.map(a=>({...a}))),[frame.id])
 useEffect(()=>{let dead=false;const img=new Image();const t=token();fetch(imageUrl(frame.id),{headers:t?{Authorization:`Bearer ${t}`}:{}}).then(r=>r.blob()).then(b=>{if(dead)return;const u=URL.createObjectURL(b);img.onload=()=>{if(dead){URL.revokeObjectURL(u);return}const c=canvas.current;if(!c)return;c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0);draft.forEach((a,i)=>{ctx.lineWidth=Math.max(2,c.width/500);ctx.strokeStyle=i===draft.length-1?'#4fe2b6':'#e5b85c';ctx.strokeRect(a.x*c.width,a.y*c.height,a.width*c.width,a.height*c.height);ctx.font=`${Math.max(12,c.width/60)}px monospace`;ctx.fillStyle=ctx.strokeStyle;ctx.fillText(a.class_code,a.x*c.width+4,Math.max(15,a.y*c.height+15))});URL.revokeObjectURL(u)};img.src=u}).catch(()=>{});return()=>{dead=true}},[frame.id,draft])
 function pos(e:React.PointerEvent){const c=canvas.current!;const r=c.getBoundingClientRect();const clamp=(v:number)=>Math.max(0,Math.min(1,v));return{x:clamp((e.clientX-r.left)/r.width),y:clamp((e.clientY-r.top)/r.height)}}
 function down(e:React.PointerEvent){start.current=pos(e);(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}
 function up(e:React.PointerEvent){if(!start.current)return;const p=pos(e),s=start.current;start.current=null;const x=Math.min(s.x,p.x),y=Math.min(s.y,p.y),w=Math.abs(p.x-s.x),h=Math.abs(p.y-s.y);if(w<.01||h<.01)return;const next=[...draft,{class_code:activeClass,x,y,width:w,height:h}];setDraft(next);onChange(next)}
 return <div className="label-canvas-wrap"><canvas ref={canvas} onPointerDown={down} onPointerUp={up}/><div className="label-canvas-help"><MousePointer2 size={14}/>Arrastrá sobre la imagen para crear una caja <b>{activeClass}</b></div></div>
}

export default function DatasetPage({me}:{me:UserMe}){
 const [overview,setOverview]=useState<Overview|null>(null),[orgId,setOrgId]=useState(me.organization_id||''),[orgs,setOrgs]=useState<Org[]>([]),[datasetId,setDatasetId]=useState(''),[work,setWork]=useState<Work|null>(null),[cams,setCams]=useState<Cam[]>([]),[cameraId,setCameraId]=useState(''),[selected,setSelected]=useState(''),[activeClass,setActiveClass]=useState('HELMET'),[draft,setDraft]=useState<Draft[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[shadow,setShadow]=useState<ShadowCam[]>([])
 const canManage=me.permission_codes.includes('ml.manage')||me.role_codes.includes('SUPERADMIN')
 const current=useMemo(()=>work?.frames.find(f=>f.id===selected)||work?.frames[0]||null,[work,selected])
 async function load(forceOrg?:string,forceDataset?:string){setMsg('');let oid=forceOrg||orgId||me.organization_id||'';if(!oid&&me.role_codes.includes('SUPERADMIN')){const oo=await api<Org[]>('/organizations');setOrgs(oo);const demo=oo.find(x=>x.code==='DEMO-HYS')||oo[0];oid=demo?.id||'';if(oid)setOrgId(oid)}const ov=await api<Overview>('/ml/overview'+(oid?`?organization_id=${oid}`:''));setOverview(ov);let did=forceDataset||datasetId||ov.datasets[0]?.id||'';setDatasetId(did);const c=await api<Cam[]>('/cameras');setCams(c);if(!cameraId&&c[0])setCameraId(c[0].id);if(did){const w=await api<Work>(`/ml/datasets/${did}/workspace`);setWork(w);if(!selected&&w.frames[0])setSelected(w.frames[0].id)}try{setShadow(await api<ShadowCam[]>('/ml/shadow/by-camera'+(oid?`?organization_id=${oid}`:'')))}catch{setShadow([])}}
 useEffect(()=>{load()},[])
 useEffect(()=>{if(datasetId)api<Work>(`/ml/datasets/${datasetId}/workspace`).then(w=>{setWork(w);setSelected(w.frames[0]?.id||'')})},[datasetId])
 async function createDataset(){setBusy(true);try{const code=`HYS-PPE-${new Date().toISOString().slice(0,10).replaceAll('-','')}`;const r=await api<{id:string}>('/ml/datasets',{method:'POST',body:JSON.stringify({organization_id:orgId||me.organization_id||undefined,code,name:'Dataset HYS PPE Real',license_name:'PROPRIETARY-HYS'})});setDatasetId(r.id);setMsg('Dataset creado. Ya podés capturar frames reales.');await load(orgId||me.organization_id||'',r.id)}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 async function capture(){if(!datasetId||!cameraId)return;setBusy(true);try{const r=await api<{captured:number}>(`/ml/datasets/${datasetId}/capture/camera/${cameraId}`,{method:'POST',body:JSON.stringify({count:5,interval_ms:500})});setMsg(`${r.captured} frames capturados desde cámara.`);await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 async function uploadVideo(file:File){if(!datasetId)return;setBusy(true);try{const fd=new FormData();fd.append('file',file);fd.append('every_seconds','1');fd.append('max_frames','120');const h=new Headers();const t=token();if(t)h.set('Authorization',`Bearer ${t}`);const r=await fetch(`${API}/ml/datasets/${datasetId}/capture/video`,{method:'POST',headers:h,body:fd});if(!r.ok){const b=await r.json();throw new Error(b.detail||'Error de carga')}const j=await r.json();setMsg(`${j.captured} frames extraídos del video.`);await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 async function curate(status:'ACCEPTED'|'REJECTED'|'PENDING'){if(!current)return;await api(`/ml/frames/${current.id}/curation`,{method:'PATCH',body:JSON.stringify({status})});await load()}
 async function saveGT(verified:boolean){if(!current)return;setBusy(true);try{await api(`/ml/frames/${current.id}/annotations`,{method:'PUT',body:JSON.stringify({annotations:draft,verified})});setMsg(verified?'Ground Truth verificado.':'Etiquetas guardadas como borrador.');await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 async function freeze(){if(!datasetId)return;const version=`v${String(new Date().getTime()).slice(-6)}`;setBusy(true);try{const r=await api<any>(`/ml/datasets/${datasetId}/freeze-visual`,{method:'POST',body:JSON.stringify({version,classes:['HELMET','VEST','SAFETY_SHOES']})});setMsg(`Dataset ${r.version} congelado: ${r.manifest.image_count} imágenes / ${r.manifest.annotation_count} boxes.`)}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 return <div className="dataset-workspace">
  <section className="dataset-command"><div><div className="eyebrow">BLOQUE 10 · v1.1.0 · DATASET HYS</div><h3>Dataset Manager Visual y Ground Truth</h3><p>Capturá desde cámara o video, descartá duplicados, etiquetá cajas manualmente y congelá datasets propios para entrenamiento y evaluación.</p></div><div className="dataset-license"><ShieldCheck/><div><span>CADENA DE CUSTODIA</span><b>DATASET PROPIO HYS</b><small>SHA-256 · origen · cámara · curación · verificación humana</small></div></div></section>
  <div className="dataset-toolbar">{me.role_codes.includes('SUPERADMIN')&&orgs.length>0&&<select value={orgId} onChange={e=>{const v=e.target.value;setOrgId(v);setDatasetId('');setTimeout(()=>load(v,''),0)}}>{orgs.map(o=><option key={o.id} value={o.id}>{o.code} — {o.name}</option>)}</select>}<select value={datasetId} onChange={e=>setDatasetId(e.target.value)}><option value="">Dataset…</option>{overview?.datasets.map(d=><option key={d.id} value={d.id}>{d.code} — {d.name}</option>)}</select>{canManage&&<button onClick={createDataset} disabled={busy}><Database size={14}/>NUEVO DATASET</button>}<button onClick={()=>load()}><RefreshCw size={14}/>ACTUALIZAR</button></div>
  {!datasetId?<div className="dataset-empty"><Database/><b>No hay dataset HYS</b><span>Creá el primero para comenzar la captura real.</span></div>:<>
   <section className="dataset-kpis"><div><Images/><span>TOTAL</span><b>{work?.stats.TOTAL??0}</b></div><div><CheckCircle2/><span>ACEPTADOS</span><b>{work?.stats.ACCEPTED??0}</b></div><div><XCircle/><span>RECHAZADOS</span><b>{work?.stats.REJECTED??0}</b></div><div><ScanSearch/><span>GROUND TRUTH</span><b>{work?.stats.VERIFIED??0}</b></div><div><MousePointer2/><span>BOXES</span><b>{work?.stats.ANNOTATIONS??0}</b></div></section>
   <section className="capture-strip"><div><select value={cameraId} onChange={e=>setCameraId(e.target.value)}>{cams.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name} · {c.status}</option>)}</select><button disabled={!canManage||busy||!cameraId} onClick={capture}><Video size={15}/>CAPTURAR 5 FRAMES</button></div><label className="upload-video"><Upload size={15}/>SUBIR VIDEO<input type="file" accept="video/*" disabled={!canManage||busy} onChange={e=>e.target.files?.[0]&&uploadVideo(e.target.files[0])}/></label><button disabled={!canManage||busy} onClick={freeze}><Database size={15}/>CONGELAR VERSIÓN</button></section>
   {msg&&<div className="dataset-message">{msg}</div>}
   <section className="dataset-editor-grid"><div className="frame-browser"><div className="panel-title"><span>CURACIÓN</span><em>{work?.frames.length||0}</em></div><div className="frame-list">{work?.frames.map(f=><button key={f.id} className={current?.id===f.id?'frame-item active':'frame-item'} onClick={()=>{setSelected(f.id);setDraft(f.annotations.map(a=>({...a})))}}><AuthThumb id={f.id}/><div><b>{f.source_type}</b><span>{f.curation_status} · {f.ground_truth_status}</span><small>{f.annotations.length} boxes</small></div></button>)}</div></div>
    <div className="label-editor">{current?<><div className="label-tools"><select value={activeClass} onChange={e=>setActiveClass(e.target.value)}>{work?.classes.map(c=><option key={c}>{c}</option>)}</select><button onClick={()=>{const n=draft.slice(0,-1);setDraft(n)}}><Trash2 size={14}/>ÚLTIMA</button><button onClick={()=>saveGT(false)}>GUARDAR</button><button className="verify" onClick={()=>saveGT(true)}><CheckCircle2 size={14}/>VERIFICAR GT</button></div><LabelCanvas frame={current} activeClass={activeClass} onChange={setDraft}/><div className="curation-actions"><button onClick={()=>curate('REJECTED')}><XCircle/>RECHAZAR</button><button onClick={()=>curate('PENDING')}>PENDIENTE</button><button className="accept" onClick={()=>curate('ACCEPTED')}><CheckCircle2/>ACEPTAR</button></div></>:<div className="dataset-empty"><Images/><b>Sin frames</b><span>Capturá desde una cámara o subí un video.</span></div>}</div>
   </section>
   <section className="shadow-camera-panel"><div className="panel-title"><span>EVALUACIÓN SHADOW POR CÁMARA</span><em>TIEMPO REAL</em></div><div className="shadow-camera-grid">{shadow.map(s=><div key={s.camera_id}><FileVideo2/><span>{s.camera_code}</span><b>{s.samples?`${(s.agreement_ratio*100).toFixed(1)}%`:'SIN MUESTRAS'}</b><small>{s.samples} observaciones · {s.agreements} acuerdos</small></div>)}</div></section>
  </>}</div>
}
