import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,CheckCircle2,Clock3,Download,Eye,FileVideo,RefreshCw,ShieldAlert,ShieldCheck,UserCheck,XCircle} from 'lucide-react'
import {api,apiBlob,UserMe} from './api'

type Summary={active:number;critical_active:number;high_active:number;closed_today:number;total:number}
type Event={id:string;event_number:string;camera_code?:string;camera_name?:string;zone_code?:string;zone_name?:string;track_id:string;ppe_code:string;ppe_name:string;severity:string;status:string;detection_status:string;confirmed_at:string;last_seen_at:string;ended_at?:string|null;duration_seconds:number;last_confidence?:number|null;consensus_ratio:number;missing_observations:number;evaluable_observations:number;close_reason?:string|null;operational_status:string;review_outcome:string;assigned_to_user_id?:string|null;assigned_to_name?:string|null;acknowledged_by_name?:string|null;acknowledged_at?:string|null;reviewed_by_name?:string|null;reviewed_at?:string|null;resolved_by_name?:string|null;resolved_at?:string|null;review_notes?:string|null;resolution_note?:string|null;evidence_status:string;evidence_count:number;evidence_error?:string|null;response_seconds?:number|null;resolution_seconds?:number|null}
type Evidence={id:string;kind:string;mime_type:string;sha256:string;size_bytes:number;captured_at:string;source_frame_at?:string|null;immutable:boolean;metadata_json:any}
type Timeline={id:string;type:string;action?:string|null;body?:string|null;actor_name?:string|null;from_status?:string|null;to_status?:string|null;details:any;created_at:string}
type Assignee={id:string;full_name:string;email:string}

function fmt(sec:number){if(sec<60)return `${sec.toFixed(1)} s`;const m=Math.floor(sec/60),s=Math.round(sec%60);return `${m}m ${s}s`}
function bytes(n:number){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}

export default function EventsPage({me}:{me:UserMe}){
  const [summary,setSummary]=useState<Summary|null>(null),[events,setEvents]=useState<Event[]>([]),[status,setStatus]=useState('OPEN'),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Event|null>(null)
  const [evidence,setEvidence]=useState<Evidence[]>([]),[timeline,setTimeline]=useState<Timeline[]>([]),[assignees,setAssignees]=useState<Assignee[]>([]),[note,setNote]=useState(''),[msg,setMsg]=useState('')
  const canRead=me.permission_codes.includes('safety_event.read')||me.role_codes.includes('SUPERADMIN'),canManage=me.permission_codes.includes('safety_event.manage')||me.role_codes.includes('SUPERADMIN')
  async function refresh(){if(!canRead)return;setBusy(true);try{const [s,e]=await Promise.all([api<Summary>('/safety-events/summary'),api<Event[]>(`/safety-events${status?`?status=${status}`:''}`)]);setSummary(s);setEvents(e);if(selected){const fresh=e.find(x=>x.id===selected.id);if(fresh)setSelected(fresh)}}finally{setBusy(false)}}
  async function loadDetail(e:Event){setSelected(await api<Event>(`/safety-events/${e.id}`));const jobs:any[]=[api<Evidence[]>(`/safety-events/${e.id}/evidence`),api<Timeline[]>(`/safety-events/${e.id}/timeline`)];if(canManage)jobs.push(api<Assignee[]>(`/safety-events/assignees?event_id=${e.id}`));const out=await Promise.all(jobs);setEvidence(out[0] as Evidence[]);setTimeline(out[1] as Timeline[]);if(canManage)setAssignees(out[2] as Assignee[]);setMsg('')}
  useEffect(()=>{refresh();const id=setInterval(refresh,2500);return()=>clearInterval(id)},[status])
  const title=useMemo(()=>status==='OPEN'?'EVENTOS ACTIVOS':status==='CLOSED'?'HISTORIAL CERRADO':'TODOS LOS EVENTOS',[status])
  async function act(path:string,body?:any){if(!selected)return;setMsg('');try{await api(`/safety-events/${selected.id}/${path}`,{method:'POST',body:body?JSON.stringify(body):undefined});await loadDetail(selected);await refresh();setMsg('Acción registrada y auditada.')}catch(e){setMsg((e as Error).message)}}
  async function openEvidence(e:Evidence){const blob=await apiBlob(`/safety-events/evidence/${e.id}/preview`);const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),120000)}
  async function downloadEvidence(e:Evidence){const blob=await apiBlob(`/safety-events/evidence/${e.id}/content`);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${e.kind.toLowerCase()}-${e.id.slice(0,8)}${e.mime_type.startsWith('video')?'.mp4':'.jpg'}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
  if(!canRead)return <div className="vision-no-camera">Sin permiso para consultar Safety Events.</div>
  return <div className="events-workspace block6">
    <section className="event-command"><div><div className="eyebrow">GESTIÓN OPERATIVA · BLOQUE 6 · v0.7.0 + HF 0.7.2</div><h3>Alertas, evidencia y revisión humana inicial</h3><p>La detección automática y la decisión humana permanecen separadas. Toda acción operativa queda trazada; la evidencia se almacena con SHA-256 y sin endpoints de modificación o borrado.</p></div><div className="event-human"><ShieldCheck/><span>HUMAN-IN-THE-LOOP<br/><b>REVISIÓN OPERATIVA ACTIVA</b></span></div></section>
    <section className="event-metrics"><div><ShieldAlert/><span>ACTIVOS</span><b>{summary?.active??'—'}</b></div><div><AlertTriangle/><span>CRÍTICOS</span><b>{summary?.critical_active??'—'}</b></div><div><AlertTriangle/><span>ALTOS</span><b>{summary?.high_active??'—'}</b></div><div><Clock3/><span>CERRADOS HOY</span><b>{summary?.closed_today??'—'}</b></div></section>
    <div className="event-toolbar"><div><button className={status==='OPEN'?'chip active':'chip'} onClick={()=>setStatus('OPEN')}>ACTIVOS</button><button className={status==='CLOSED'?'chip active':'chip'} onClick={()=>setStatus('CLOSED')}>CERRADOS</button><button className={status===''?'chip active':'chip'} onClick={()=>setStatus('')}>TODOS</button></div><button className="icon-button" onClick={refresh}><RefreshCw size={14}/>{busy?'Actualizando…':'Actualizar'}</button></div>
    <div className={selected?'event-master-detail selected':'event-master-detail'}>
      <section className="events-panel"><div className="panel-title"><span>{title}</span><em>{events.length}</em></div>{!events.length?<div className="events-empty"><ShieldCheck/><b>Sin eventos en este estado</b><span>El motor no inventa alertas cuando la evidencia temporal no alcanza los umbrales configurados.</span></div>:<div className="event-list">{events.map(e=><article className={`event-card ${e.severity.toLowerCase()} ${selected?.id===e.id?'selected':''}`} key={e.id} onClick={()=>loadDetail(e)}><div className="event-severity">{e.severity}</div><div className="event-main"><div><small>{e.event_number}</small><h4>{e.ppe_name} · {e.detection_status}</h4><p>{e.camera_code} · {e.zone_code||'SIN ZONA'} · {e.track_id}</p><div className="op-badges"><span>{e.operational_status}</span><span>{e.review_outcome}</span><span>{e.evidence_status} · {e.evidence_count}</span>{e.assigned_to_name&&<span>{e.assigned_to_name}</span>}</div></div><div className="event-stats"><span>CONSENSO <b>{Math.round(e.consensus_ratio*100)}%</b></span><span>OBS. <b>{e.missing_observations}/{e.evaluable_observations}</b></span><span>DURACIÓN <b>{fmt(e.duration_seconds)}</b></span></div></div><div className="event-foot"><span>{e.status}</span><span>{new Date(e.confirmed_at).toLocaleString()}</span>{e.close_reason&&<span>{e.close_reason}</span>}</div></article>)}</div>}</section>
      {selected&&<aside className="event-detail"><div className="detail-head"><div><small>{selected.event_number}</small><h3>{selected.ppe_name}</h3><p>{selected.camera_code} · {selected.zone_code||'SIN ZONA'} · {selected.track_id}</p></div><button onClick={()=>setSelected(null)}>×</button></div>
        <div className="detail-grid"><div><span>OPERATIVO</span><b>{selected.operational_status}</b></div><div><span>REVISIÓN</span><b>{selected.review_outcome}</b></div><div><span>RESPUESTA</span><b>{selected.response_seconds!=null?fmt(selected.response_seconds):'Pendiente'}</b></div><div><span>RESOLUCIÓN</span><b>{selected.resolution_seconds!=null?fmt(selected.resolution_seconds):'—'}</b></div></div>
        {canManage&&<div className="ops-actions"><button disabled={!!selected.acknowledged_at} onClick={()=>act('acknowledge')}><UserCheck size={14}/>RECONOCER</button><select value={selected.assigned_to_user_id||''} onChange={e=>act('assign',{user_id:e.target.value||null})}><option value="">Sin responsable</option>{assignees.map(x=><option value={x.id} key={x.id}>{x.full_name}</option>)}{!assignees.length&&<option value="" disabled>No hay responsables habilitados</option>}</select><button onClick={()=>act('review',{outcome:'CONFIRMED',notes:note||null})}><CheckCircle2 size={14}/>CONFIRMAR</button><button onClick={()=>act('review',{outcome:'FALSE_POSITIVE',notes:note||'Clasificado como falso positivo'})}><XCircle size={14}/>FALSO POSITIVO</button></div>}
        <div className="detail-section"><div className="panel-title"><span>EVIDENCIAS</span><em>{evidence.length}</em></div>{!evidence.length?<p className="muted">Evidencia pendiente o no disponible.</p>:<div className="evidence-list">{evidence.map(x=><div className="evidence-row" key={x.id}><button className="evidence-preview" onClick={()=>openEvidence(x)}>{x.mime_type.startsWith('video')?<FileVideo/>:<Eye/>}<span><b>{x.kind}</b><small>{bytes(x.size_bytes)} · SHA {x.sha256.slice(0,12)}…</small>{x.mime_type.startsWith('video')&&<small>PREVIEW H.264 BROWSER-COMPATIBLE</small>}</span></button><button className="evidence-download" title="Descargar evidencia original inmutable" onClick={()=>downloadEvidence(x)}><Download size={14}/></button></div>)}</div>}{selected.evidence_error&&<small className="error-text">{selected.evidence_error}</small>}</div>
        {canManage&&<div className="detail-section"><div className="panel-title"><span>OBSERVACIÓN</span><em>INMUTABLE</em></div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Registrar contexto operativo, verificación en campo o justificación…"/><div className="note-buttons"><button disabled={!note.trim()} onClick={()=>act('notes',{body:note}).then(()=>setNote(''))}>AGREGAR NOTA</button><button disabled={!note.trim()} onClick={()=>act('resolve',{note}).then(()=>setNote(''))}>RESOLVER OPERATIVAMENTE</button></div></div>}
        <div className="detail-section"><div className="panel-title"><span>TRAZABILIDAD</span><em>{timeline.length}</em></div><div className="timeline">{timeline.map(x=><div key={x.id}><i/><span><b>{x.type==='NOTE'?x.action:x.action}</b><small>{x.actor_name||'SISTEMA'} · {new Date(x.created_at).toLocaleString()}</small>{x.body&&<p>{x.body}</p>}</span></div>)}</div></div>{msg&&<div className="detail-message">{msg}</div>}
      </aside>}
    </div>
  </div>
}
