import {useEffect,useMemo,useRef,useState} from 'react'
import {Activity,BrainCircuit,CircleDot,Cpu,RefreshCw,ScanLine,ShieldCheck,TimerReset,UserRoundSearch,Filter,UsersRound,TriangleAlert} from 'lucide-react'
import {API,api,token,UserMe} from './api'

type VisionCam={
  camera_id:string;camera_code:string;camera_name:string;camera_status:string;enabled:boolean;
  inference_fps:number;min_confidence:number;nms_iou_threshold:number;tracker_iou_threshold:number;
  tracker_max_missed_frames:number;tracker_min_hits_to_confirm:number;min_box_area_ratio:number;
  max_box_area_ratio:number;min_height_ratio:number;min_aspect_ratio:number;max_aspect_ratio:number;
  top_band_reject_y_ratio:number;top_band_reject_bottom_ratio:number;ppe_enabled:boolean;ppe_min_visibility_ratio:number;ppe_uncertainty_margin:number;
  compliance_enabled:boolean;compliance_window_seconds:number;compliance_min_persistence_seconds:number;compliance_min_consensus_ratio:number;compliance_min_missing_observations:number;compliance_cooldown_seconds:number;compliance_clear_grace_seconds:number;compliance_track_absence_close_seconds:number;
  model:{code:string;name:string;provider:string;backend:string;version:string;license_name:string;license_url?:string;commercial_use:boolean};
  ppe_model?:{code:string;name:string;provider:string;backend:string;version:string;license_name:string;license_url?:string;commercial_use:boolean;metadata?:Record<string,unknown>}|null
}

type Runtime={
  camera_id:string;captured_at?:string;inference_at?:string;model?:string;model_version?:string;backend?:string;
  persons:number;confirmed_persons?:number;active_tracks?:number;raw_detections?:number;filtered_detections?:number;
  candidate_tracks?:number;false_candidate_rejections?:number;hardening_version?:string;ppe_enabled?:boolean;ppe_model?:string;ppe_backend?:string;
  rejection_breakdown?:Record<string,number>;compliance_enabled?:boolean;compliance_summary?:{non_compliant:number;unknown:number;compliant:number;no_aplica:number;actions:string[]};
  tracks:Array<{track_id:string;bbox:number[];confidence:number;age_frames:number;hits?:number;missed_frames:number;state?:string;zones:Array<{id:string;code:string;name:string}>;ppe?:Record<string,{status:'OK'|'NO_DETECTADO'|'INCIERTO'|'NO_VISIBLE';confidence:number|null;visible_ratio:number;region_bbox:number[]}>;compliance?:Array<{ppe_code:string;ppe_name:string;zone_code?:string;severity:string;observed_status:string;compliance_status:'COMPLIANT'|'NON_COMPLIANT'|'UNKNOWN'|'NO_APLICA';consensus_ratio:number;missing_observations:number;evaluable_observations:number;event_active:boolean}>}>;
  inference_ms?:number;inference_fps_target?:number;status?:string
}
type Worker={status:string;heartbeat_age_seconds:number|null;backend:string|null}

function Overlay({cameraId,enabled,ppeEnabled}:{cameraId:string;enabled:boolean;ppeEnabled:boolean}){
  const [src,setSrc]=useState(''),previous=useRef<string|null>(null)
  useEffect(()=>{let stop=false;if(!cameraId)return;async function tick(){try{const t=token();const r=await fetch(`${API}/vision/cameras/${cameraId}/overlay.jpg`,{headers:t?{Authorization:`Bearer ${t}`}:{}});if(!r.ok)return;const b=await r.blob(),u=URL.createObjectURL(b);if(stop){URL.revokeObjectURL(u);return}if(previous.current)URL.revokeObjectURL(previous.current);previous.current=u;setSrc(u)}catch{}}tick();const id=setInterval(tick,700);return()=>{stop=true;clearInterval(id);if(previous.current)URL.revokeObjectURL(previous.current)}},[cameraId])
  return <div className="vision-stage">{src?<img src={src} alt="Overlay IA"/>:<div className="vision-empty"><ScanLine/><b>ESPERANDO FRAME</b></div>}<div className="vision-overlay-tag"><CircleDot size={11}/>{!enabled?'IA PERSONAS DESACTIVADA':ppeEnabled?'PERSON + EPP ACTIVOS':'IA PERSONAS ACTIVA'}</div></div>
}

export default function VisionPage({me}:{me:UserMe}){
  const [cams,setCams]=useState<VisionCam[]>([]),[selected,setSelected]=useState(''),[runtime,setRuntime]=useState<Runtime|null>(null),[worker,setWorker]=useState<Worker|null>(null),[msg,setMsg]=useState('')
  const canManage=me.permission_codes.includes('vision.manage')||me.role_codes.includes('SUPERADMIN')
  const cam=useMemo(()=>cams.find(c=>c.camera_id===selected)||cams[0]||null,[cams,selected])
  async function refresh(){const [c,w]=await Promise.all([api<VisionCam[]>('/vision/cameras'),api<Worker>('/vision/worker')]);setCams(c);setWorker(w);if(!selected&&c[0])setSelected(c[0].camera_id)}
  useEffect(()=>{refresh()},[])
  useEffect(()=>{if(!cam)return;let stop=false;async function poll(){try{const r=await api<Runtime>(`/vision/cameras/${cam.camera_id}/runtime`);if(!stop)setRuntime(r)}catch{}}poll();const id=setInterval(poll,850);return()=>{stop=true;clearInterval(id)}},[cam?.camera_id])
  async function patch(body:Record<string,unknown>){if(!cam)return;setMsg('');try{await api(`/vision/cameras/${cam.camera_id}/settings`,{method:'PATCH',body:JSON.stringify(body)});setMsg('Configuración de visión actualizada.');await refresh()}catch(e){setMsg((e as Error).message)}}
  const confirmed=runtime?.confirmed_persons??runtime?.persons??0
  const tracks=runtime?.active_tracks??runtime?.tracks?.filter(x=>x.missed_frames===0).length??0
  return <div className="vision-workspace">
    <section className="vision-command"><div><div className="eyebrow">VISIÓN ARTIFICIAL · BLOQUE 5 · v0.6.0</div><h3>Persona → TRACK → regiones corporales → EPP asociado</h3><p>Casco, chaleco y calzado se evalúan dentro del mismo TRACK. El motor de cumplimiento aplica zonas, reglas, persistencia y consenso; NO_VISIBLE e INCIERTO nunca generan Safety Events.</p></div><div className={`worker-chip ${worker?.status||'offline'}`}><span className="pulse"/><div><small>VISION ENGINE</small><strong>{worker?.status?.toUpperCase()||'CONSULTANDO'}</strong></div></div></section>
    <div className="vision-selector"><label>CÁMARA<select value={cam?.camera_id||''} onChange={e=>setSelected(e.target.value)}>{cams.map(c=><option value={c.camera_id} key={c.camera_id}>{c.camera_code} — {c.camera_name}</option>)}</select></label><button className="icon-button" onClick={refresh}><RefreshCw size={14}/>Actualizar</button></div>
    {!cam?<div className="vision-no-camera">No hay cámaras configuradas para visión.</div>:<>
      <section className="vision-grid"><div className="vision-main"><Overlay cameraId={cam.camera_id} enabled={cam.enabled} ppeEnabled={cam.ppe_enabled}/>
        <div className="vision-metrics"><div><UserRoundSearch/><span>PERSONAS CONFIRMADAS</span><b>{confirmed}</b></div><div><ScanLine/><span>TRACKS ACTIVOS</span><b>{tracks}</b></div><div><TimerReset/><span>INFERENCIA</span><b>{runtime?.inference_ms!=null?`${runtime.inference_ms.toFixed(0)} ms`:'—'}</b></div><div><Activity/><span>OBJETIVO</span><b>{cam.inference_fps.toFixed(1)} FPS</b></div></div>
        <div className="vision-quality-strip"><div><UsersRound/><span>RAW</span><b>{runtime?.raw_detections??0}</b></div><div><Filter/><span>FILTRADAS</span><b>{runtime?.filtered_detections??0}</b></div><div><BrainCircuit/><span>CANDIDATOS</span><b>{runtime?.candidate_tracks??0}</b></div><div><TriangleAlert/><span>RECHAZOS</span><b>{runtime?.false_candidate_rejections??0}</b></div></div>
        <div className="compliance-summary"><div><span>CUMPLEN</span><b>{runtime?.compliance_summary?.compliant??0}</b></div><div><span>POTENCIALES FALTAS</span><b>{runtime?.compliance_summary?.non_compliant??0}</b></div><div><span>INCIERTOS</span><b>{runtime?.compliance_summary?.unknown??0}</b></div><div><span>NO APLICA</span><b>{runtime?.compliance_summary?.no_aplica??0}</b></div></div>
        <div className="tracks-panel"><div className="panel-title"><span>TRACKS CONFIRMADOS</span><em>ANÓNIMOS · MIN {cam.tracker_min_hits_to_confirm} HITS</em></div>{!runtime?.tracks?.length?<div className="tracks-empty">No hay personas confirmadas en el frame actual.</div>:runtime.tracks.filter(t=>t.missed_frames===0).map(t=><div className="track-row ppe-track-row" key={t.track_id}><strong>{t.track_id}</strong><span>CONF {Math.round(t.confidence*100)}%</span><span>{t.zones.length?t.zones.map(z=>z.code).join(' · '):'FUERA DE ZONA'}</span><div className="ppe-statuses">{(['HELMET','VEST','SAFETY_SHOES'] as const).map(code=>{const st=t.ppe?.[code];return <div className={`ppe-state ${(st?.status||'NO_VISIBLE').toLowerCase()}`} key={code}><b>{code==='HELMET'?'CASCO':code==='VEST'?'CHALECO':'CALZADO'}</b><span>{st?.status||'NO_VISIBLE'}</span><small>{st?.confidence!=null?`${Math.round(st.confidence*100)}%`:`VIS ${(st?.visible_ratio??0)*100|0}%`}</small></div>})}</div><div className="compliance-track">{(t.compliance||[]).map(c=><div className={`compliance-pill ${c.compliance_status.toLowerCase()}`} key={`${t.track_id}-${c.ppe_code}`}><b>{c.ppe_name}</b><span>{c.compliance_status}</span><small>{c.zone_code||'—'} · {c.severity} · CONS {Math.round(c.consensus_ratio*100)}%{c.event_active?' · EVENTO ACTIVO':''}</small></div>)}</div></div>)}</div>
      </div><aside className="vision-config"><div className="panel-title"><span>PIPELINE ENDURECIDO</span><em>PERSON</em></div><div className="model-card"><BrainCircuit/><div><small>MODELO</small><strong>{cam.model.name}</strong><span>{cam.model.version} · {cam.model.backend}</span></div></div><div className="license-card"><ShieldCheck/><div><b>{cam.model.license_name}</b><span>{cam.model.commercial_use?'USO COMERCIAL HABILITADO':'REVISAR LICENCIA'}</span></div></div><button className={cam.enabled?'vision-toggle on':'vision-toggle'} disabled={!canManage} onClick={()=>patch({enabled:!cam.enabled})}>{cam.enabled?'DESACTIVAR IA PERSONAS':'ACTIVAR IA PERSONAS'}</button>
        <div className="ppe-model-card"><div className="panel-title"><span>MODELO EPP</span><em>HELMET · VEST · SHOES</em></div><strong>{cam.ppe_model?.name||'PPE model pendiente'}</strong><small>{cam.ppe_model?.version||'—'} · {cam.ppe_model?.backend||'—'}</small><p>Baseline ML propio para puesta en marcha; sin pesos de terceros. Requiere calibración con dataset real antes de producción.</p></div>
        <button className={cam.ppe_enabled?'vision-toggle on':'vision-toggle'} disabled={!canManage||!cam.enabled} onClick={()=>patch({ppe_enabled:!cam.ppe_enabled})}>{cam.ppe_enabled?'DESACTIVAR IA EPP':'ACTIVAR IA EPP'}</button>
        <label>Visibilidad mínima EPP<input type="number" min="0.25" max="1" step="0.05" value={cam.ppe_min_visibility_ratio} disabled={!canManage} onChange={e=>patch({ppe_min_visibility_ratio:Number(e.target.value)})}/></label>
        <label>Margen de incertidumbre<input type="number" min="0" max="0.3" step="0.01" value={cam.ppe_uncertainty_margin} disabled={!canManage} onChange={e=>patch({ppe_uncertainty_margin:Number(e.target.value)})}/></label>
        <label>FPS de inferencia<input type="number" min="0.2" max="10" step="0.2" value={cam.inference_fps} disabled={!canManage} onChange={e=>patch({inference_fps:Number(e.target.value)})}/></label>
        <label>Confidence mínimo<input type="number" min="0.05" max="0.99" step="0.01" value={cam.min_confidence} disabled={!canManage} onChange={e=>patch({min_confidence:Number(e.target.value)})}/></label>
        <label>NMS IoU<input type="number" min="0.05" max="0.95" step="0.05" value={cam.nms_iou_threshold} disabled={!canManage} onChange={e=>patch({nms_iou_threshold:Number(e.target.value)})}/></label>
        <label>IoU tracker<input type="number" min="0.01" max="0.95" step="0.05" value={cam.tracker_iou_threshold} disabled={!canManage} onChange={e=>patch({tracker_iou_threshold:Number(e.target.value)})}/></label>
        <label>Hits para confirmar TRACK<input type="number" min="2" max="20" value={cam.tracker_min_hits_to_confirm} disabled={!canManage} onChange={e=>patch({tracker_min_hits_to_confirm:Number(e.target.value)})}/></label>
        <label>Frames perdidos tolerados<input type="number" min="1" max="60" value={cam.tracker_max_missed_frames} disabled={!canManage} onChange={e=>patch({tracker_max_missed_frames:Number(e.target.value)})}/></label>
        <details className="vision-advanced"><summary>Filtros geométricos avanzados</summary><label>Área mínima<input type="number" min="0.0005" max="0.5" step="0.005" value={cam.min_box_area_ratio} disabled={!canManage} onChange={e=>patch({min_box_area_ratio:Number(e.target.value)})}/></label><label>Área máxima<input type="number" min="0.01" max="1" step="0.01" value={cam.max_box_area_ratio} disabled={!canManage} onChange={e=>patch({max_box_area_ratio:Number(e.target.value)})}/></label><label>Altura mínima<input type="number" min="0.02" max="0.95" step="0.02" value={cam.min_height_ratio} disabled={!canManage} onChange={e=>patch({min_height_ratio:Number(e.target.value)})}/></label><label>Aspecto min / max<div className="vision-pair"><input type="number" min="0.05" max="2" step="0.05" value={cam.min_aspect_ratio} disabled={!canManage} onChange={e=>patch({min_aspect_ratio:Number(e.target.value)})}/><input type="number" min="0.1" max="4" step="0.05" value={cam.max_aspect_ratio} disabled={!canManage} onChange={e=>patch({max_aspect_ratio:Number(e.target.value)})}/></div></label></details>
        <div className="compliance-config"><div className="panel-title"><span>MOTOR CUMPLIMIENTO</span><em>TEMPORAL</em></div><button className={cam.compliance_enabled?'vision-toggle on':'vision-toggle'} disabled={!canManage||!cam.ppe_enabled} onClick={()=>patch({compliance_enabled:!cam.compliance_enabled})}>{cam.compliance_enabled?'DESACTIVAR CUMPLIMIENTO':'ACTIVAR CUMPLIMIENTO'}</button><label>Ventana temporal (s)<input type="number" min="1" max="60" step="0.5" value={cam.compliance_window_seconds} disabled={!canManage} onChange={e=>patch({compliance_window_seconds:Number(e.target.value)})}/></label><label>Persistencia mínima (s)<input type="number" min="0.2" max="30" step="0.5" value={cam.compliance_min_persistence_seconds} disabled={!canManage} onChange={e=>patch({compliance_min_persistence_seconds:Number(e.target.value)})}/></label><label>Consenso mínimo<input type="number" min="0.5" max="1" step="0.05" value={cam.compliance_min_consensus_ratio} disabled={!canManage} onChange={e=>patch({compliance_min_consensus_ratio:Number(e.target.value)})}/></label><label>Observaciones faltantes mínimas<input type="number" min="2" max="100" value={cam.compliance_min_missing_observations} disabled={!canManage} onChange={e=>patch({compliance_min_missing_observations:Number(e.target.value)})}/></label><label>Cooldown (s)<input type="number" min="0" max="3600" step="1" value={cam.compliance_cooldown_seconds} disabled={!canManage} onChange={e=>patch({compliance_cooldown_seconds:Number(e.target.value)})}/></label></div>
        <div className="vision-note"><Cpu/><span>PERSON y EPP son proveedores desacoplados. El EPP se asocia por regiones de cabeza, torso y pies del mismo TRACK; NO_VISIBLE se conserva como estado distinto de NO_DETECTADO.</span></div>{msg&&<div className="camera-message">{msg}</div>}</aside></section>
    </>}
  </div>
}
